# Generated by Django 3.0.7 on 2020-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('trips', models.ManyToManyField(related_name='trips', to='trips.Trip')),
            ],
        ),
    ]
