# Generated by Django 3.0.7 on 2020-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
