# Generated by Django 3.0.7 on 2020-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_users'),
        ('pins', '0004_auto_20200612_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='pins', to='trips.Trip'),
        ),
    ]
