# Generated by Django 3.0.7 on 2020-06-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_auto_20200615_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='trips',
            new_name='pins',
        ),
    ]
