# Generated by Django 3.0.7 on 2020-06-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_auto_20200615_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='pins',
            new_name='trips',
        ),
    ]
