# Generated by Django 3.0.7 on 2020-06-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_auto_20200615_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='address',
            field=models.CharField(default='59D Josephine Avenue, London', max_length=500),
            preserve_default=False,
        ),
    ]
