# Generated by Django 3.0.7 on 2020-06-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200607_1737'),
        ('requests', '0002_request_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Club'),
        ),
    ]
