# Generated by Django 3.0.7 on 2020-06-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_members'),
        ('chats', '0002_auto_20200606_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_chat', to='clubs.Club'),
        ),
    ]
