# Generated by Django 3.0.7 on 2020-06-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200607_1737'),
        ('chats', '0006_auto_20200609_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_club', to='clubs.Club'),
        ),
    ]
