# Generated by Django 3.0.7 on 2020-06-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messsages', '0002_auto_20200606_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
